### PR TITLE
Remove dependency to VisPy Visual base class

### LINKED ISSUE #605: All views are broken on VisPy master
This is only a problem when using VisPy master, not when using the latest stable release (v0.4.0).

The visual interface has changed. A solution might be to not derive from base visuals, since we currently don't use any of the functionality.

### PR DESCRIPTION
**Pull request by rossant**
Fixes #605

### CODE REVIEW

**Comment by rossant** [comment]
@nippoo I've disabled circle CI for now (it needs to be configured)
this can be merged if travis and appveyor are happy

**Comment by nippoo** [comment]
... but sadly, they are noit

**Comment by rossant** [comment]
travis is now happy but not appveyor. it tries to use python 3.3 but we officially don't support this version! could you have a look?

**Comment by nippoo** [comment]
Uhhhh...

```
File "C:\Users\appveyor\miniconda3\lib\site-packages\pytestqt\qt_compat.py", line 54, in _import_module
    m = __import__(_root_module, globals(), locals(), [module_name], 0)
ImportError: Module use of python33.dll conflicts with this version of Python.
```

Looks like this is a problem with `pytestqt` no?

**Comment by nippoo** [comment]
Or rather with the `conda` build of it?

**Comment by nippoo** [comment]
Woop, fixed now. Bug filed with `conda`. https://github.com/conda/conda/issues/1505

**Pull request merged**
