### PR TITLE
Update some data structures in controller

### PR DESCRIPTION
**Pull request by rossant**

### CODE REVIEW

**Comment by nippoo** [comment]
Haha, this is the same as what I'd done. I'm not sure if this introduces any weird bugs though...?

**Comment by rossant** [comment]
Of course this is a quick hack, the whole controller thing must be improved but I can't do it right now...

**Comment by nippoo** [comment]
Awesome! Sorry - just merged this and saw it was still in progress - works for me, anyway :)

**Comment by rossant** [comment]
no no it's fine, it wasn't `[WIP]`

**Pull request merged**
