### PR TITLE
Optimizations in phy.plot

### LINKED ISSUE #688: Display bug with markers in feature view

### PR DESCRIPTION
**Pull request by rossant**
* Move data normalization of waveforms, templates to controller in order to leverage caching
* Remove unnecessary array copies in transforms
* Add new `Uniform*` visuals that share colors and other data, to save memory. These uniforms are mask- and depth- aware. The computation of the mask-dependent colors is ported to the GPU (based on RGB-HSV transform).
* Closes #688

### CODE REVIEW

**Comment by rossant** [comment]
@yger @nsteinme this was way harder than anticipated, for a modest speed improvement. :( Could you please try this PR along with the corresponding [PR in phycontrib](https://github.com/kwikteam/phy-contrib/pull/24). If you have any problem, please comment here with all details and, if necessary, send me your dataset.

**Comment by yger** [comment]
Ok, great, I'll give it a try and let you know !

Best

Pierre

2016-04-05 14:29 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by yger** [comment]
Ok, I'm testing it, but what should I see? This PR is just about speed
improvements? If yes, I'll give it a try with large datasets, because
otherwise, except the final error message in the shell about divide that is
gone, everthing look similar to normal

Best

Pierre

2016-04-05 14:35 GMT+02:00 Pierre Yger <pierre.yger@gmail.com>:

**Comment by rossant** [comment]
Yes, on SSD it should be marginally faster. On HDD you shouldn't see any difference.

**Comment by rossant** [comment]
If things work normally that's already good given the extensive changes in the code! :)

**Comment by yger** [comment]
Ok, so far this is good. I'm able to open 1517 channels with the GUI, in a
decent time for loading it! I'll try 4225 channels soon.

Meanwhile, I'll continue testing and I'll report some bugs if any by
creating issues ( I think I already spotted some minor issues, so I'll
create tickets)

Best

Pierre

Le mar. 5 avr. 2016 16:28, Cyrille Rossant <notifications@github.com> a
écrit :

**Comment by rossant** [comment]
@yger do you have your SSD already?

**Comment by yger** [comment]
On the main sorting machines, not yet, but on my laptop yes. I can feel a
slight difference in responsiveness, but I'll test more in depth. And
tomorrow I'll post some minor tickets regarding toggling number over
channels in TraceView and some zoom issues, that are still not consistent
when changing templates.

Best

Pierre

Le mar. 5 avr. 2016 20:20, Cyrille Rossant <notifications@github.com> a
écrit :

**Comment by rossant** [comment]
The difference when switching from HDD to SDD will only appear when the cache is initially empty. It if is already populated, the difference will be minimal.

Also you can see [this PR](https://github.com/kwikteam/phy-contrib/pull/25) to precache the data when first opening the dataset.

**Comment by rossant** [comment]
I'm going to merge this. @yger @nsteinme if you have further problems, please open new issues, *one issue per problem* if possible. Thanks

**Comment by yger** [comment]
Ok, no problem, thanks!

**Pull request merged**
