### PR TITLE
Remove UI code

### PR DESCRIPTION
**Pull request by rossant**
* [x] Removed all IPython/UI-related code.
* [x] Refactor waveform/session bindings so that the UI can easily bind VisPy and IPython views on the session
* [x] on_select: pass selector instance
* [x] waveform view: no more cluster metadata but pass colors directly

Closes #119.

### CODE REVIEW

**Comment by rossant** [comment]
@ctaf42 @nippoo ready for review/merge

There is no more UI code in phy. In phy-ui you can instanciate a Session and extend it with action and VisPy/IPython views. The `start_manual_clustering()` function is done: you'll have to implement it in phy-ui. See [here](https://github.com/kwikteam/phy/pull/121/files#diff-bb1eb32858d033c80533de69ed9bb7d6R149) for an example.

**Comment by ctaf42** [comment]
Everything done and in a working state with the previous PR in phy and the
head of phy-ui.

**Comment by ctaf42** [comment]
why should we keep the plot code in phy?

**Comment by rossant** [comment]
> why should we keep the plot code in phy?

Because phy implements plotting functionality based on VisPy and matplotlib, and this is orthogonal to the web-based UI in phy-ui.

**Comment by ctaf42** [comment]
which is also orthogonal to the content of phy no?

should it be in a another repo?

**Comment by rossant** [comment]
No I think it's fine in phy, because it's still pure Python, and still in scope for phy (analysis of ephys signals). Splitting phy-ui made sense because it's especially HTML/CSS/JS.

**Comment by ctaf42** [comment]
ok can you fix phy-ui please, now that you changed the interface.

**Comment by rossant** [comment]
sure I'm on it

**Comment by rossant** [comment]
@nippoo I think you can merge this now (phyui has been adapted)

**Comment by ctaf42** [comment]
LGTM

**Pull request merged**
