### PR TITLE
Added 7 more colours to COLORMAP

### PR DESCRIPTION
**Pull request by nippoo**
For @shabnamkadir

### CODE REVIEW

**Comment by nippoo** [comment]
Fixes #595

**Comment by rossant** [comment]
how did you choose the colors?

**Comment by nippoo** [comment]
via k-means clustering http://tools.medialab.sciences-po.fr/iwanthue/

**Comment by rossant** [comment]
awesome!

**Comment by shabnamkadir** [comment]
Yay! Thanks @nippoo! ;-)

**Pull request merged**
