### PR TITLE
Improve manual clustering component

### PR DESCRIPTION
**Pull request by rossant**
*  Improve selection of next cluster after merge and move
* Add `label` action in `ManualClustering`
* Fixes kwikteam/phy-contrib#38
* Fixes kwikteam/phy-contrib#70

### CODE REVIEW

**Comment by rossant** [comment]
@nsteinme this is still experimental -- feel free to test

**Comment by rossant** [comment]
@nsteinme in this PR, you can do `:l blah bleh` after selecting clusters, and it will create `cluster_blah.csv`. Feel free to try. You also need https://github.com/kwikteam/phy-contrib/pull/71

**Comment by nsteinme** [comment]
Awesome, will try it!

**Comment by nsteinme** [comment]
So this one is not working. In one situation it worked for me, but in other situations it selects the next cluster in _similarity view_ rather than the next in cluster view. I don't have a full theory of what works and what doesn't but if you try this I think it'll fail: select a cluster, spacebar, g [merge], spacebar, spacebar, alt+g. I think it will select a similarity view cluster rather than a cluster view cluster (it should always select a cluster view cluster!).

**Comment by rossant** [comment]
ok, update and try again?

**Comment by rossant** [comment]
@nsteinme `:label` now applies to clusters from the cluster view only

**Pull request merged**
